spring:
  datasource:
    url: jdbc:postgresql://ec2-34-247-172-149.eu-west-1.compute.amazonaws.com:5432/d7o8e8b15reasp
    username: zuillhqppuydiz
    password: 47862c3675afd9fb342526278ceef2601a7df38e98e1c0d88070b827d8083bf7
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL95Dialect